replicaCount: 1

image:
  repository: "<docker_registry_url>/<image_name>"
  tag: "dev-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: "dev_port"
  targetPort: 8000 # App port

appConfig:
  debug: "False"

django:
  debug: "False"
  allowedHosts: "*"
