apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: app
          image: {{IMAGE}}
          ports:
            - containerPort: 8000
