---
- name: Setup Kubernetes Environment (Root Mode)
  hosts: all
  become: yes
  # Всі дії будуть виконуватися від імені root, оскільки він є ansible_user

  tasks:
    - name: Update apt and install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - conntrack
          - socat
          - docker.io
        update_cache: yes
        state: present

    - name: Install Minikube & Kubectl
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      loop:
        - { url: 'https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64', dest: '/usr/local/bin/minikube' }
        - { url: 'https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl', dest: '/usr/local/bin/kubectl' }

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Start Minikube as Root
      # Для root ми використовуємо --force, бо minikube не любить запускатися від root за замовчуванням
      shell: minikube start --driver=docker --listen-address=0.0.0.0 --force
      args:
        creates: /root/.kube/config

    - name: Setup Kubectl Proxy (Requirement)
      # Запускаємо проксі у фоні на порту 8001
      shell: "nohup kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' > /root/proxy.log 2>&1 &"
      async: 10
      poll: 0
