name: "Ansible Deploy"

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types: [completed]

jobs:
  ansible:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    
    defaults:
      run:
        working-directory: task2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          # tr -d '\r' — це магічна команда, яка робить ключ "робочим" для Ansible
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > task2/id_rsa
          chmod 600 task2/id_rsa

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Ansible Check Mode (Dry Run)
        run: |
          ansible-playbook -i inventory.ini setup.yml --check \
          -e "ansible_host=${{ secrets.VM_IP }}" \
          --private-key id_rsa \
          --ssh-common-args='-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey'
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Ansible Playbook Apply
        if: success()
        run: |
          ansible-playbook -i inventory.ini setup.yml \
          -e "ansible_host=${{ secrets.VM_IP }}" \
          --private-key id_rsa \
          --ssh-common-args='-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey'
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
